version: '3.3'

services:
  web:
    build: .
    command: bash -c "sh run-django.sh"
    volumes:
      - .:/code
    ports:
      - 5000:8000

# ports - 5000:8000 
# host:container
#    host:5000
#    container:8000
